const ROLES = {
  PRODUCTEUR: 'PRODUCTEUR',
  RESPONSABLE_PRODUCTION: 'RESPONSABLE_PRODUCTION',
  TECHNICIEN_COORDINATEUR: 'TECHNICIEN_COORDINATEUR',
  RESPONSABLE_ADMINISTRATIF: 'RESPONSABLE_ADMINISTRATIF',
  RESPONSABLE_PUBLICITE: 'RESPONSABLE_PUBLICITE',
  RECEPTIONNISTE_POLICIER: 'RECEPTIONNISTE_POLICIER',
  RESPONSABLE_SECURITE: 'RESPONSABLE_SECURITE',
  RESPONSABLE: 'RESPONSABLE',
};

const ALL_ROLES = Object.values(ROLES);

const GUIDE_STATUSES = [
  'DRAFT',
  'SUBMITTED',
  'APPROVED',
  'FINAL_PUBLISHED',
  'LIVE_IN_PROGRESS',
  'LIVE_STOPPED',
  'ARCHIVED',
  'REJECTED',
];

module.exports = { ROLES, ALL_ROLES, GUIDE_STATUSES };
