export const ALL_ROLES = [
  'PRODUCTEUR',
  'RESPONSABLE_PRODUCTION',
  'TECHNICIEN_COORDINATEUR',
  'RESPONSABLE_ADMINISTRATIF',
  'RESPONSABLE_PUBLICITE',
  'RECEPTIONNISTE_POLICIER',
  'RESPONSABLE_SECURITE',
  'RESPONSABLE',
]
