import api from '../../api/axios'
export const getGuides = (params) => api.get('/guides', { params })
export const getGuide = (id) => api.get(`/guides/${id}`)
export const getGuestConflicts = (id) => api.get(`/guides/${id}/guest-conflicts`)
export const checkGuestConflict = (name, date, excludeId) => api.get('/guides/check-guest', { params: { name, date, excludeId } })
export const createGuide = (data) => api.post('/guides', data)
export const updateGuide = (id, data) => api.put(`/guides/${id}`, data)
export const submitGuide = (id) => api.patch(`/guides/${id}/submit`)
export const approveGuide = (id) => api.patch(`/guides/${id}/approve`)
export const publishGuide = (id) => api.patch(`/guides/${id}/publish`)
export const validateGuide = (id) => api.patch(`/guides/${id}/validate`)
export const rejectGuide = (id, data) => api.patch(`/guides/${id}/reject`, data)
export const startLiveGuide = (id) => api.patch(`/guides/${id}/start-live`)
export const stopLiveGuide = (id) => api.patch(`/guides/${id}/stop-live`)
export const restartLiveGuide = (id) => api.patch(`/guides/${id}/restart-live`)
export const archiveGuide = (id) => api.patch(`/guides/${id}/archive`)
export const deleteGuide = (id) => api.delete(`/guides/${id}`)
// Segments (with embedded guest info)
export const getSegments = (guideId) => api.get(`/guides/${guideId}/segments`)
export const createSegment = (guideId, data) => api.post(`/guides/${guideId}/segments`, data)
export const updateSegment = (guideId, id, data) => api.put(`/guides/${guideId}/segments/${id}`, data)
export const deleteSegment = (guideId, id) => api.delete(`/guides/${guideId}/segments/${id}`)
export const completeSegment = (guideId, id) => api.patch(`/guides/${guideId}/segments/${id}/complete`)
export const uploadSegmentPhoto = (guideId, id, formData) => api.post(`/guides/${guideId}/segments/${id}/upload-photo`, formData, { headers: { 'Content-Type': 'multipart/form-data' } })
// Songs
export const getSongs = (guideId) => api.get(`/guides/${guideId}/songs`)
export const createSong = (guideId, data) => api.post(`/guides/${guideId}/songs`, data)
export const updateSong = (guideId, id, data) => api.put(`/guides/${guideId}/songs/${id}`, data)
export const deleteSong = (guideId, id) => api.delete(`/guides/${guideId}/songs/${id}`)
export const validateSong = (guideId, id) => api.patch(`/guides/${guideId}/songs/${id}/validate`)
export const checkDuplicateSong = (guideId, title) => api.get(`/guides/${guideId}/songs/check-duplicate`, { params: { title } })
// Notes
export const getNotes = (guideId) => api.get(`/guides/${guideId}/notes`)
export const createNote = (guideId, data) => api.post(`/guides/${guideId}/notes`, data)
export const updateNote = (guideId, noteId, data) => api.put(`/guides/${guideId}/notes/${noteId}`, data)
export const deleteNote = (guideId, noteId) => api.delete(`/guides/${guideId}/notes/${noteId}`)
// Guests
export const getGuests = (guideId) => api.get(`/guides/${guideId}/guests`)
export const createGuest = (guideId, data) => api.post(`/guides/${guideId}/guests`, data)
export const updateGuest = (guideId, id, data) => api.put(`/guides/${guideId}/guests/${id}`, data)
export const deleteGuest = (guideId, id) => api.delete(`/guides/${guideId}/guests/${id}`)
export const uploadGuestPhoto = (guideId, id, formData) => api.post(`/guides/${guideId}/guests/${id}/upload-photo`, formData, { headers: { 'Content-Type': 'multipart/form-data' } })
export const deleteGuestPhoto = (guideId, id, data) => api.post(`/guides/${guideId}/guests/${id}/delete-photo`, data)
export const replaceGuestPhoto = (guideId, id, formData) => api.post(`/guides/${guideId}/guests/${id}/replace-photo`, formData, { headers: { 'Content-Type': 'multipart/form-data' } })
// Song history (cross-guide validated songs)
export const getValidatedSongs = (params) => api.get('/songs/history', { params })
export const updateSongGenre = (id, genre) => api.patch(`/songs/history/genre/${id}`, { genre })
export const getSongGenreStats = (params) => api.get('/songs/history/genre-stats', { params })
export const deleteHistorySong = (id) => api.delete(`/songs/history/${id}`)
export const classifySongByApi = (id) => api.post(`/songs/history/classify/${id}`)
// Winners
export const getWinners = (guideId) => api.get(`/guides/${guideId}/winners`)
export const createWinner = (guideId, data) => api.post(`/guides/${guideId}/winners`, data)
export const updateWinner = (guideId, id, data) => api.put(`/guides/${guideId}/winners/${id}`, data)
export const sendWinnersToPublicity = (guideId) => api.post(`/guides/${guideId}/winners/send-to-publicity`)
export const receiveWinner = (guideId, id, data = {}) => api.patch(`/guides/${guideId}/winners/${id}/receive`, data)
export const deleteWinner = (guideId, id) => api.delete(`/guides/${guideId}/winners/${id}`)
export const getBlacklist = (params) => api.get('/winners/blacklist', { params })
